apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-hello
spec:
  steps:
    - name: sayhello
      image: ubuntu
      command:
      - /bin/bash
      args: 
      - '-c'
      - 'echo "hello world"'