apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-name-pipeline
spec:
  params: 
    - name: who
      type: string
  tasks:
    - name: say-hello
      taskRef: 
        name: hello-task
    - name: say-hello-name
      taskRef:
        name: "hello-name-task"
      params:
        - name: who
          value: "$(params.who)"