apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-name-task
spec:
  params:
    - name: who
      type: string
      default: World
  steps:
    - name: say-hello
      image: ubuntu
      command:
        - /bin/bash
      args: ['-c', 'echo hello $(params.who)']